import unittest
from pathlib import Path

from fastapi.testclient import TestClient

from tests._env import setup_test_environment

setup_test_environment()

from src.db import engine
from src.main import app


class UiContractTests(unittest.TestCase):
    @classmethod
    def tearDownClass(cls) -> None:
        engine.dispose()

    def test_landing_uses_its_dedicated_lottie_mascot_without_touching_chat(self) -> None:
        with TestClient(app) as client:
            landing_response = client.get("/")
            chat_response = client.get("/app/")
            asset_response = client.get("/landing-static/zito-mascot.svg")
            logo_response = client.get("/landing-static/zito-logo.svg")
            lottie_response = client.get("/landing-static/zito-lottie/zito-lottie.json")
            runtime_response = client.get("/landing-static/zito-lottie/lottie_canvas.min.js")
            fallback_response = client.get("/landing-static/zito-lottie/assets/zito-fallback.svg")
            arm_response = client.get("/landing-static/zito-lottie/assets/zito-arm.svg")
            intro_controller_response = client.get("/landing-static/zito-intro-mascot.js")
            intro_lottie_response = client.get("/landing-static/zito-intro-lottie/zito-intro-lottie.json")
            intro_source_response = client.get("/landing-static/zito-intro-lottie/source/zito-intro.svg")
            intro_eyes_response = client.get("/landing-static/zito-intro-lottie/assets/zito-intro-eyes.svg")
            intro_mouth_response = client.get("/landing-static/zito-intro-lottie/assets/zito-intro-mouth.svg")
            obsolete_intro_foot_response = client.get("/landing-static/zito-intro-lottie/assets/zito-intro-foot.svg")
            obsolete_arm_response = client.get("/landing-static/zito-lottie/assets/zito-arm.png")
            obsolete_asset_responses = [
                client.get(f"/landing-static/{name}")
                for name in (
                    "logo-z.png",
                    "logo-z-transparent.png",
                    "rocket-svgrepo-com.svg",
                    "zito-avatar.png",
                    "zito-avatar-transparent.png",
                )
            ]

        self.assertEqual(landing_response.status_code, 200)
        self.assertEqual(chat_response.status_code, 200)
        self.assertEqual(asset_response.status_code, 200)
        self.assertEqual(asset_response.headers["content-type"], "image/svg+xml")
        self.assertEqual(logo_response.status_code, 200)
        self.assertEqual(logo_response.headers["content-type"], "image/svg+xml")
        self.assertIn('viewBox="0 0 795.78 889.5"', logo_response.text)
        self.assertIn('id="linear-gradient"', logo_response.text)
        self.assertEqual(lottie_response.status_code, 200)
        self.assertEqual(runtime_response.status_code, 200)
        self.assertEqual(fallback_response.status_code, 200)
        self.assertEqual(arm_response.status_code, 200)
        self.assertEqual(arm_response.headers["content-type"], "image/svg+xml")
        self.assertEqual(intro_controller_response.status_code, 200)
        self.assertEqual(intro_lottie_response.status_code, 200)
        self.assertEqual(intro_source_response.status_code, 200)
        self.assertEqual(intro_source_response.headers["content-type"], "image/svg+xml")
        self.assertEqual(intro_eyes_response.status_code, 200)
        self.assertEqual(intro_eyes_response.headers["content-type"], "image/svg+xml")
        self.assertEqual(intro_mouth_response.status_code, 200)
        self.assertEqual(intro_mouth_response.headers["content-type"], "image/svg+xml")
        self.assertEqual(obsolete_intro_foot_response.status_code, 404)
        self.assertEqual(obsolete_arm_response.status_code, 404)
        self.assertTrue(all(response.status_code == 404 for response in obsolete_asset_responses))
        self.assertIn("/landing-static/zito-mascot.js", landing_response.text)
        self.assertIn("/landing-static/zito-intro-mascot.js", landing_response.text)
        self.assertIn("<zito-lottie-mascot", landing_response.text)
        self.assertNotIn('class="avatar-img"', landing_response.text)
        self.assertNotIn("mascot-glow", landing_response.text)
        self.assertNotIn("@keyframes floaty", landing_response.text)
        self.assertIn("/landing-static/zito-logo.svg", landing_response.text)
        self.assertIn("/landing-static/zito-logo.svg", chat_response.text)
        self.assertNotIn("/landing-static/logo-z-transparent.png", landing_response.text)
        self.assertNotIn("/landing-static/logo-z-transparent.png", chat_response.text)
        self.assertEqual(chat_response.text.count("/landing-static/zito-mascot.svg"), 3)
        self.assertIn("object-fit: contain", landing_response.text)
        self.assertIn("object-fit: contain", chat_response.text)
        self.assertIn("Light cosmic theme", landing_response.text)
        self.assertIn('id="resendOtp"', landing_response.text)
        self.assertIn('id="phoneActionSlot"', landing_response.text)
        self.assertIn('id="otpEntry"', landing_response.text)
        self.assertNotIn('id="nameForm"', landing_response.text)
        self.assertNotIn('id="otpForm"', landing_response.text)
        self.assertIn("normalizeDigits", landing_response.text)
        self.assertIn("right: calc(50% + 52px)", landing_response.text)
        self.assertIn("right: calc(50% + 40px)", landing_response.text)
        self.assertIn("border-left: 16px solid var(--bubble-fill)", landing_response.text)
        self.assertIn("<zito-intro-lottie-mascot", landing_response.text)
        self.assertNotIn('class="intro-avatar"', landing_response.text)

    def test_landing_lottie_contract_has_real_canvas_timeline_and_accessibility(self) -> None:
        lottie = Path("landing/zito-lottie/zito-lottie.json").read_text(encoding="utf-8")
        controller = Path("landing/zito-mascot.js").read_text(encoding="utf-8")

        self.assertIn('"wave"', lottie)
        self.assertIn('"smile"', lottie)
        self.assertIn('"idle"', lottie)
        self.assertIn('"Raised arm from source SVG"', lottie)
        self.assertIn('"Smile from source SVG"', lottie)
        self.assertIn('"r"', lottie)
        self.assertIn('"s"', lottie)
        self.assertIn('"p": "zito-arm.svg"', lottie)
        self.assertNotIn('"p": "zito-arm.png"', lottie)
        self.assertIn('renderer: "canvas"', controller)
        self.assertIn("IntersectionObserver", controller)
        self.assertIn("prefers-reduced-motion", controller)
        self.assertIn("WAVE_COOLDOWN_MS", controller)
        self.assertIn("playSegments", controller)
        self.assertIn("suspend()", controller)
        self.assertIn("isSuspended", controller)
        self.assertNotIn("requestAnimationFrame", controller)
        self.assertNotIn("rive", controller.lower())

        intro_lottie = Path("landing/zito-intro-lottie/zito-intro-lottie.json").read_text(encoding="utf-8")
        intro_controller = Path("landing/zito-intro-mascot.js").read_text(encoding="utf-8")
        self.assertIn('"eyes-look-up"', intro_lottie)
        self.assertIn('"Eyes from source SVG looking upward"', intro_lottie)
        self.assertIn('"Smile from source SVG"', intro_lottie)
        self.assertIn('"p": "zito-intro-eyes.svg"', intro_lottie)
        self.assertIn('"p": "zito-intro-mouth.svg"', intro_lottie)
        self.assertNotIn('"foot-tap"', intro_lottie)
        self.assertNotIn('"Ground contact beneath front shoe"', intro_lottie)
        self.assertIn('"s"', intro_lottie)
        self.assertIn('"p"', intro_lottie)
        self.assertIn('renderer: "canvas"', intro_controller)
        self.assertIn("IntersectionObserver", intro_controller)
        self.assertIn("prefers-reduced-motion", intro_controller)
        self.assertIn("activate()", intro_controller)
        self.assertIn("deactivate()", intro_controller)
        self.assertNotIn("requestAnimationFrame", intro_controller)
        self.assertNotIn("rive", intro_controller.lower())

        admin_template = Path("src/templates/admin.html").read_text(encoding="utf-8")
        admin_login_template = Path("src/templates/admin_login.html").read_text(encoding="utf-8")
        self.assertIn("/landing-static/zito-logo.svg", admin_template)
        self.assertIn("/landing-static/zito-logo.svg", admin_login_template)

    def test_landing_uses_stacked_light_autofill_fields(self) -> None:
        with TestClient(app) as client:
            response = client.get("/")

        self.assertEqual(response.status_code, 200)
        html = response.text
        self.assertIn("flex-direction: column", html)
        self.assertIn("color-scheme: light", html)
        self.assertIn("Light cosmic theme", html)
        self.assertIn(".phone-input:-webkit-autofill", html)
        self.assertIn('label for="fullNameInput"', html)
        self.assertIn('label for="phoneInput"', html)
        self.assertIn("display_name: pendingFullName || null", html)
        self.assertIn('data-step="details"', html)
        self.assertIn("phoneForm.dataset.step === 'otp'", html)
        self.assertIn("otpEntry.hidden = false", html)
        self.assertIn("fetch('/api/me')", html)
        self.assertNotIn("localStorage.setItem('zito_user_id'", html)
        self.assertNotIn("fullName.split(/\\s+/)", html)
        self.assertNotIn('id="nameForm"', html)
        self.assertNotIn('id="otpForm"', html)
        self.assertLess(html.index('id="fullNameInput"'), html.index('id="phoneInput"'))

    def test_landing_has_a_continuous_zito_introduction_view(self) -> None:
        with TestClient(app) as client:
            response = client.get("/")
            ambient_script = client.get("/landing-static/ambient-audio.js")
            ambient_track = client.get("/landing-static/zito-ambient.mp3")

        self.assertEqual(response.status_code, 200)
        self.assertEqual(ambient_script.status_code, 200)
        self.assertEqual(ambient_track.status_code, 200)
        self.assertIn("audio/mpeg", ambient_track.headers["content-type"])
        self.assertIn('id="introView"', response.text)
        self.assertIn('id="introStart"', response.text)
        self.assertIn('id="soundToggle"', response.text)
        self.assertIn("زیتو چیه؟", response.text)
        self.assertIn("زیتو یه همراه هوشمند تو در مسیر یادگیریه.", response.text)
        self.assertIn("آماده‌ای برای شروع", response.text)
        self.assertIn("showIntro", response.text)
        self.assertIn("startAmbientSound", response.text)
        self.assertIn("stopAmbientSound", response.text)
        self.assertIn('rel="preload" href="/landing-static/zito-ambient.mp3"', response.text)
        self.assertIn("/landing-static/zito-ambient.mp3", ambient_script.text)
        self.assertIn("track.loop = true", ambient_script.text)
        self.assertIn("attemptAutoplay();", ambient_script.text)
        self.assertIn("zito:landing-sound-muted", ambient_script.text)

    def test_chat_personalizes_avatar_welcome_without_second_greeting(self) -> None:
        with TestClient(app) as client:
            response = client.get("/app/")
            glass_response = client.get("/landing-static/zito-glass.css")

        self.assertEqual(response.status_code, 200)
        self.assertEqual(glass_response.status_code, 200)
        html = response.text
        glass_css = glass_response.text
        self.assertIn('id="welcomeTitle"', html)
        self.assertIn('id="welcomeSub"', html)
        self.assertIn("سلام ${firstName}، من زیتو هستم", html)
        self.assertIn("خوشحالم که اینجایی", html)
        self.assertIn('question: "حوزه کاری یا رشته تحصیلی‌ات چیه؟"', html)
        self.assertIn('key: "education_level"', html)
        self.assertIn('key: "daily_learning_time_text"', html)
        self.assertIn('key: "preferred_career_path"', html)
        self.assertIn('api("/api/me/profile"', html)
        self.assertIn('id="courseList"', html)
        self.assertIn('id="stagePathList"', html)
        self.assertIn('id="learningSidebarToggle"', html)
        self.assertIn('id="learningSidebarScrim"', html)
        self.assertIn('title="نمایش یا پنهان‌کردن سرفصل‌ها"', html)
        self.assertIn("/api/learning/enrollments/current", html)
        self.assertIn("data-complete-stage", html)
        self.assertIn("path.modules", html)
        self.assertIn("module-path-list", html)
        self.assertIn('role="list" aria-label="سرفصل‌های دوره"', html)
        self.assertIn("path-module-state", html)
        self.assertNotIn("renderModuleStageOverview", html)
        self.assertNotIn("inspectModule", html)
        self.assertIn("function setLearningSidebarOpen", html)
        self.assertIn('window.matchMedia("(max-width: 1020px)")', html)
        self.assertIn("openCoachForCurrentLesson", html)
        self.assertIn("data-open-coach", html)
        self.assertIn("showLearningAdvanceToast", html)
        self.assertIn("stageCompleted = result.stage_completed !== false", html)
        self.assertIn('completeButton.textContent = "در حال باز کردن قدم بعدی..."', html)
        self.assertNotIn("showCoachingCheckpoint", html)
        self.assertIn('aria-current="step"', html)
        self.assertIn("STAGE_LABELS", html)
        self.assertIn("holoFlow", html)
        self.assertIn("module-stage-map", html)
        self.assertIn("prefers-reduced-motion", html)
        self.assertIn("lesson.module_title", html)
        self.assertIn('id="changeCourse"', html)
        self.assertIn('id="logoutFromLearning"', html)
        self.assertIn('id="sidebarUserName"', html)
        self.assertIn('id="sidebarUserPhone"', html)
        self.assertIn("function setSidebarAccount", html)
        self.assertIn('fetch("/api/auth/logout"', html)
        self.assertLess(html.index('id="learningSidebarScrim"'), html.index('id="planetStage"'))
        self.assertIn("course-switch-icon", html)
        self.assertIn('class="lesson-coach-icon"', html)
        self.assertIn("coaching-modal", html)
        self.assertIn('class="coach-continue-icon"', html)
        self.assertIn('id="coachContinueLabel"', html)
        self.assertIn("function mediaSlotIcon", html)
        self.assertIn('id="coachForm"', html)
        self.assertIn('id="coachInput"', html)
        self.assertIn("/coach/messages", html)
        self.assertIn("coaching.enabled", html)
        self.assertIn("/app/courses/${encodeURIComponent(course.slug)}", html)
        self.assertIn("data-flashcard", html)
        self.assertIn("flashcard-stack", html)
        self.assertIn("flashcard-shadow", html)
        self.assertIn('class="flashcard-logo"', html)
        self.assertIn("data-flashcards", html)
        self.assertIn("data-flashcard-front", html)
        self.assertIn("flashcard-deal", html)
        self.assertIn("data-personalized-example", html)
        self.assertIn("data-assessment-question", html)
        self.assertIn("Focused course workspace", glass_css)
        self.assertIn("A full-height sidebar keeps navigation", glass_css)
        self.assertIn("learning-sidebar-open", glass_css)
        self.assertIn("Mobile sidebar preserves the desktop hierarchy", glass_css)
        self.assertIn("New Z stays optically centered", glass_css)
        self.assertIn("calc(100vw - 20px)", glass_css)
        self.assertIn("Choice controls read as controls", glass_css)
        self.assertIn("Coaching footer belongs to the modal surface", glass_css)
        self.assertIn("The lesson header uses the same calm", glass_css)
        self.assertIn("appearance: none", glass_css)
        self.assertIn("sidebar-action-icon", glass_css)
        self.assertIn("@media (min-width: 1021px)", glass_css)
        self.assertNotIn("/api/training/", html)
        self.assertNotIn("${firstNameOf(profile.full_name)} سلام", html)
        self.assertNotIn("/api/onboarding/${userId}/answer", html)

    def test_course_overview_is_a_separate_single_scroll_ui(self) -> None:
        with TestClient(app) as client:
            response = client.get("/app/courses/personal-development-ai")
            mascot_controller = client.get("/landing-static/course-mascot.js")
            mascot_lottie = client.get("/landing-static/course-mascot-lottie/zito-course-mascot.json")
            source_a = client.get("/landing-static/course-mascot-lottie/source/zito-state-a.svg")
            source_b = client.get("/landing-static/course-mascot-lottie/source/zito-state-b.svg")
            raster_a = client.get("/landing-static/course-mascot-lottie/assets/zito-state-a.png")
            raster_b = client.get("/landing-static/course-mascot-lottie/assets/zito-state-b.png")
            eyes_a = client.get("/landing-static/course-mascot-lottie/assets/zito-state-a-eyes-open.svg")
            mouth_b = client.get("/landing-static/course-mascot-lottie/assets/zito-state-b-mouth-open.svg")
            transition_glow = client.get("/landing-static/course-mascot-lottie/assets/zito-transition-glow.png")
            yekan_font = client.get("/landing-static/fonts/Yekan.woff2")
            glass_css = client.get("/landing-static/zito-glass.css")

        self.assertEqual(response.status_code, 200)
        self.assertEqual(mascot_controller.status_code, 200)
        self.assertEqual(mascot_lottie.status_code, 200)
        self.assertEqual(source_a.status_code, 200)
        self.assertEqual(source_b.status_code, 200)
        self.assertEqual(raster_a.status_code, 200)
        self.assertEqual(raster_b.status_code, 200)
        self.assertEqual(eyes_a.status_code, 200)
        self.assertEqual(mouth_b.status_code, 200)
        self.assertEqual(transition_glow.status_code, 200)
        self.assertEqual(yekan_font.status_code, 200)
        self.assertEqual(glass_css.status_code, 200)
        self.assertEqual(source_a.headers["content-type"], "image/svg+xml")
        self.assertEqual(source_b.headers["content-type"], "image/svg+xml")
        self.assertEqual(raster_a.headers["content-type"], "image/png")
        self.assertEqual(raster_b.headers["content-type"], "image/png")
        html = response.text
        self.assertIn('id="startCourse"', html)
        self.assertIn("/api/courses/slug/", html)
        self.assertIn("scroll-behavior: smooth", html)
        self.assertIn('font-family: "YekanZito"', html)
        self.assertIn("learning-map", html)
        self.assertIn('class="destination-panel"', html)
        self.assertIn('class="course-route learning-map"', html)
        self.assertIn('class="certificate-showcase"', html)
        self.assertIn('class="course-finish"', html)
        self.assertIn("routeModules", html)
        self.assertIn("stageDots", html)
        self.assertIn("function routeRoad", html)
        self.assertIn('class="route-road"', html)
        self.assertIn('class="route-traveler"', html)
        self.assertIn("prefers-reduced-motion", html)
        self.assertIn("/landing-static/fonts/Yekan.woff2", html)
        self.assertIn("zito-state-a.png", html)
        self.assertIn("zito-state-b.png", html)
        self.assertIn("/landing-static/course-mascot.js", html)
        self.assertIn("course-topbar-1", html)
        self.assertIn("<zito-course-mascot", html)
        self.assertNotIn("/landing-static/zito-mascot.svg", html)
        self.assertIn("/api/courses/${course.id}/enroll", html)
        self.assertIn(".zito-glass-course .topbar", glass_css.text)

        self.assertIn('"phone-pose-breathing-and-face"', mascot_lottie.text)
        self.assertIn('"laptop-pose-breathing-and-face"', mascot_lottie.text)
        self.assertEqual(mascot_lottie.text.count('"hd": true'), 4)
        self.assertIn('"soft-handoff-phone-to-laptop"', mascot_lottie.text)
        self.assertIn('"p": "zito-state-a.png"', mascot_lottie.text)
        self.assertIn('"p": "zito-state-b.png"', mascot_lottie.text)
        self.assertIn('"p": "zito-state-a-eyes-open.svg"', mascot_lottie.text)
        self.assertIn('"p": "zito-state-b-mouth-open.svg"', mascot_lottie.text)
        self.assertIn('"p": "zito-transition-glow.png"', mascot_lottie.text)
        self.assertIn('renderer: "canvas"', mascot_controller.text)
        self.assertIn("IntersectionObserver", mascot_controller.text)
        self.assertIn("prefers-reduced-motion", mascot_controller.text)

    def test_final_exam_and_certificate_have_dedicated_ui_contracts(self) -> None:
        with TestClient(app) as client:
            chat_response = client.get("/app/")
            certificate_response = client.get("/certificate/ZITO-2026-DEMO")

        self.assertEqual(chat_response.status_code, 200)
        self.assertEqual(certificate_response.status_code, 200)
        chat = chat_response.text
        certificate = certificate_response.text
        self.assertIn('id="finalExamModal"', chat)
        self.assertIn('id="finalExamBody"', chat)
        self.assertIn("requestFinalExamStart", chat)
        self.assertIn("submitFinalExam", chat)
        self.assertIn("/final-exam/start", chat)
        self.assertIn("/final-exam/attempts/", chat)
        self.assertIn("مشاهده و چاپ مدرک", chat)
        self.assertIn("@media print", certificate)
        self.assertIn("/api/certificates/", certificate)
        self.assertIn("window.print()", certificate)
        self.assertIn("گواهی پایان دوره زیتو", certificate)
        self.assertIn('class="seal"><img src="/landing-static/zito-logo.svg?v=20260905-unified-z-1"', certificate)
        self.assertNotIn('<div class="seal">Z</div>', certificate)

    def test_admin_renders_canonical_profile_without_legacy_answers(self) -> None:
        admin_template = Path("src/templates/admin.html").read_text(encoding="utf-8")
        admin_login_template = Path("src/templates/admin_login.html").read_text(encoding="utf-8")
        chat_template = Path("src/templates/chat.html").read_text(encoding="utf-8")
        self.assertIn("color-scheme: light", admin_template)
        self.assertIn("color-scheme: light", admin_login_template)
        self.assertIn("Light cosmic theme", chat_template)
        self.assertIn("user.education_level", admin_template)
        self.assertIn("user.learning_goal_interests", admin_template)
        self.assertIn("/api/admin/users/${id}/block", admin_template)
        self.assertIn("رفع مسدودیت", admin_template)
        self.assertNotIn("user.answers", admin_template)
        self.assertNotIn("/api/admin/answers/", admin_template)


if __name__ == "__main__":
    unittest.main()
